{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exitCode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV","text":"ExitCode"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The exit code for "},{"type":"codeVoice","code":"error"},{"type":"text","text":"."}]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An error to generate an exit code for."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The returned code is the same exit code that is used if "},{"type":"codeVoice","code":"error"},{"type":"text","text":" is passed"},{"type":"text","text":" "},{"type":"text","text":"to "},{"type":"codeVoice","code":"exit(withError:)"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/argumentparser\/parsablearguments\/exitcode(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ParsableArguments\/exitCode(for:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the exit code for the given error."}],"kind":"symbol","metadata":{"role":"symbol","title":"exitCode(for:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exitCode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}],"symbolKind":"method","externalID":"s:14ArgumentParser17ParsableArgumentsPAAE8exitCode3forAA04ExitF0Vs5Error_p_tFZ","extendedModule":"ArgumentParser","modules":[{"name":"ArgumentParser"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/ArgumentParser","doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ParsableArguments"]]},"references":{"doc://org.swift.docc/documentation/ArgumentParser/ParsableArguments/exitCode(for:)":{"role":"symbol","title":"exitCode(for:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exitCode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}],"abstract":[{"type":"text","text":"Returns the exit code for the given error."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ParsableArguments\/exitCode(for:)","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/parsablearguments\/exitcode(for:)"},"doc://org.swift.docc/documentation/ArgumentParser/ParsableArguments":{"role":"symbol","title":"ParsableArguments","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParsableArguments"}],"abstract":[{"type":"text","text":"A type that can be parsed from a programâ€™s command-line arguments."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ParsableArguments","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ParsableArguments"}],"url":"\/documentation\/argumentparser\/parsablearguments"},"doc://org.swift.docc/documentation/ArgumentParser/ExitCode":{"role":"symbol","title":"ExitCode","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExitCode"}],"abstract":[{"type":"text","text":"An error type that only includes an exit code."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ExitCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExitCode"}],"url":"\/documentation\/argumentparser\/exitcode"},"doc://org.swift.docc/documentation/ArgumentParser":{"role":"collection","title":"ArgumentParser","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser"}}}