{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/singleconnectionfailure\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/SingleConnectionFailure\/error","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The error we encountered."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"title":"error","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:3NIO23SingleConnectionFailureV5errors5Error_pvp","modules":[{"name":"NIO"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO","doc:\/\/org.swift.docc\/documentation\/NIO\/SingleConnectionFailure"]]},"references":{"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"},"doc://org.swift.docc/documentation/NIO/SingleConnectionFailure/error":{"role":"symbol","title":"error","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"abstract":[{"type":"text","text":"The error we encountered."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/SingleConnectionFailure\/error","kind":"symbol","type":"topic","url":"\/documentation\/nio\/singleconnectionfailure\/error"},"doc://org.swift.docc/documentation/NIO/SingleConnectionFailure":{"role":"symbol","title":"SingleConnectionFailure","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SingleConnectionFailure"}],"abstract":[{"type":"text","text":"An error that occurred during connection to a given target."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/SingleConnectionFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SingleConnectionFailure"}],"url":"\/documentation\/nio\/singleconnectionfailure"}}}