{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeRequestedDuringUnwrap"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/niossl\/niotlsunwrappingerror\/closerequestedduringunwrap"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIOSSL\/NIOTLSUnwrappingError\/closeRequestedDuringUnwrap","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"We were unwrapping the connection, but during the unwrap process a close call"},{"type":"text","text":" "},{"type":"text","text":"was made. This means the connection is now closed, not unwrapped."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeRequestedDuringUnwrap"}],"title":"NIOTLSUnwrappingError.closeRequestedDuringUnwrap","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:6NIOSSL21NIOTLSUnwrappingErrorO26closeRequestedDuringUnwrapyA2CmF","modules":[{"name":"NIOSSL"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIOSSL","doc:\/\/org.swift.docc\/documentation\/NIOSSL\/NIOTLSUnwrappingError"]]},"references":{"doc://org.swift.docc/documentation/NIOSSL/NIOTLSUnwrappingError/closeRequestedDuringUnwrap":{"role":"symbol","title":"NIOTLSUnwrappingError.closeRequestedDuringUnwrap","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeRequestedDuringUnwrap"}],"abstract":[{"type":"text","text":"We were unwrapping the connection, but during the unwrap process a close call"},{"type":"text","text":" "},{"type":"text","text":"was made. This means the connection is now closed, not unwrapped."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIOSSL\/NIOTLSUnwrappingError\/closeRequestedDuringUnwrap","kind":"symbol","type":"topic","url":"\/documentation\/niossl\/niotlsunwrappingerror\/closerequestedduringunwrap"},"doc://org.swift.docc/documentation/NIOSSL":{"role":"collection","title":"NIOSSL","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIOSSL","kind":"symbol","type":"topic","url":"\/documentation\/niossl"},"doc://org.swift.docc/documentation/NIOSSL/NIOTLSUnwrappingError":{"role":"symbol","title":"NIOTLSUnwrappingError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NIOTLSUnwrappingError"}],"abstract":[{"type":"text","text":"Represents errors that may occur while attempting to unwrap TLS from a connection."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIOSSL\/NIOTLSUnwrappingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NIOTLSUnwrappingError"}],"url":"\/documentation\/niossl\/niotlsunwrappingerror"}}}