{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToValidateHostname"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIOSSL\/NIOSSLExtraError","preciseIdentifier":"s:6NIOSSL16NIOSSLExtraErrorV","text":"NIOSSLExtraError"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/niossl\/niosslextraerror\/failedtovalidatehostname"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIOSSL\/NIOSSLExtraError\/failedToValidateHostname","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"NIOSSL was unable to validate the hostname presented by the remote peer."}],"kind":"symbol","metadata":{"role":"symbol","title":"failedToValidateHostname","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToValidateHostname"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NIOSSLExtraError","preciseIdentifier":"s:6NIOSSL16NIOSSLExtraErrorV"}],"symbolKind":"property","externalID":"s:6NIOSSL16NIOSSLExtraErrorV24failedToValidateHostnameACvpZ","extendedModule":"NIOSSL","modules":[{"name":"NIOSSL"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIOSSL","doc:\/\/org.swift.docc\/documentation\/NIOSSL\/NIOSSLExtraError"]]},"references":{"doc://org.swift.docc/documentation/NIOSSL/NIOSSLExtraError":{"role":"symbol","title":"NIOSSLExtraError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NIOSSLExtraError"}],"abstract":[{"type":"text","text":"This structure contains errors added to NIOSSL after the original "},{"type":"codeVoice","code":"NIOSSLError"},{"type":"text","text":" enum was"},{"type":"text","text":" "},{"type":"text","text":"shipped. This is an extensible error object that allows us to evolve it going forward."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIOSSL\/NIOSSLExtraError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NIOSSLExtraError"}],"url":"\/documentation\/niossl\/niosslextraerror"},"doc://org.swift.docc/documentation/NIOSSL/NIOSSLExtraError/failedToValidateHostname":{"role":"symbol","title":"failedToValidateHostname","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToValidateHostname"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NIOSSLExtraError","preciseIdentifier":"s:6NIOSSL16NIOSSLExtraErrorV"}],"abstract":[{"type":"text","text":"NIOSSL was unable to validate the hostname presented by the remote peer."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIOSSL\/NIOSSLExtraError\/failedToValidateHostname","kind":"symbol","type":"topic","url":"\/documentation\/niossl\/niosslextraerror\/failedtovalidatehostname"},"doc://org.swift.docc/documentation/NIOSSL":{"role":"collection","title":"NIOSSL","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIOSSL","kind":"symbol","type":"topic","url":"\/documentation\/niossl"}}}