{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"i386_exception_state_t"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","text":"__darwin_i386_exception_state"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/i386_exception_state_t"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/i386_exception_state_t","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"i386_exception_state_t"}],"title":"i386_exception_state_t","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:@T@i386_exception_state_t","modules":[{"name":"NIO"}],"navigatorTitle":[{"kind":"identifier","text":"i386_exception_state_t"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO"]]},"references":{"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"},"doc://org.swift.docc/documentation/NIO/i386_exception_state_t":{"role":"symbol","title":"i386_exception_state_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"i386_exception_state_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/i386_exception_state_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"i386_exception_state_t"}],"url":"\/documentation\/nio\/i386_exception_state_t"}}}