{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NIOFcntlFailedError"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This error should never happen, unfortunately, we have seen this happen on Darwin."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/niofcntlfailederror"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.swift.docc\/s5ErrorP","doc:\/\/org.swift.docc\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/NIOFcntlFailedError","interfaceLanguage":"swift"},"abstract":[{"type":"codeVoice","code":"NIOFcntlFailedError"},{"type":"text","text":" indicates that NIO was unable to perform an"},{"type":"text","text":" "},{"type":"text","text":"operation on a socket."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NIOFcntlFailedError"}],"title":"NIOFcntlFailedError","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:3NIO19NIOFcntlFailedErrorV","modules":[{"name":"NIO"}],"navigatorTitle":[{"kind":"identifier","text":"NIOFcntlFailedError"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO"]]},"references":{"doc://org.swift.docc/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/org.swift.docc\/s5ErrorP"},"doc://org.swift.docc/documentation/NIO/NIOFcntlFailedError":{"role":"symbol","title":"NIOFcntlFailedError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NIOFcntlFailedError"}],"abstract":[{"type":"codeVoice","code":"NIOFcntlFailedError"},{"type":"text","text":" indicates that NIO was unable to perform an"},{"type":"text","text":" "},{"type":"text","text":"operation on a socket."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/NIOFcntlFailedError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NIOFcntlFailedError"}],"url":"\/documentation\/nio\/niofcntlfailederror"},"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"},"doc://org.swift.docc/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.swift.docc\/s8SendableP"}}}