{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"task_get_exception_ports_info"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"port"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/mach_port_t","preciseIdentifier":"c:@T@mach_port_t","text":"mach_port_t"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"exception_mask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_mask_t","preciseIdentifier":"c:@T@exception_mask_t","text":"exception_mask_t"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"masks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_mask_array_t","preciseIdentifier":"c:@T@exception_mask_array_t","text":"exception_mask_array_t"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"masksCnt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/mach_msg_type_number_t","preciseIdentifier":"c:@T@mach_msg_type_number_t","text":"mach_msg_type_number_t"},{"kind":"text","text":">!, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"old_handlers_info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_handler_info_array_t","preciseIdentifier":"c:@T@exception_handler_info_array_t","text":"exception_handler_info_array_t"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"old_behaviors"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_behavior_array_t","preciseIdentifier":"c:@T@exception_behavior_array_t","text":"exception_behavior_array_t"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"old_flavors"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_flavor_array_t","preciseIdentifier":"c:@T@exception_flavor_array_t","text":"exception_flavor_array_t"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/kern_return_t","preciseIdentifier":"c:@T@kern_return_t","text":"kern_return_t"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/task_get_exception_ports_info(_:_:_:_:_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/task_get_exception_ports_info(_:_:_:_:_:_:_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"task_get_exception_ports_info"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mach_port_t","preciseIdentifier":"c:@T@mach_port_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"exception_mask_t","preciseIdentifier":"c:@T@exception_mask_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"exception_mask_array_t","preciseIdentifier":"c:@T@exception_mask_array_t"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"mach_msg_type_number_t","preciseIdentifier":"c:@T@mach_msg_type_number_t"},{"kind":"text","text":">!, "},{"kind":"typeIdentifier","text":"exception_handler_info_array_t","preciseIdentifier":"c:@T@exception_handler_info_array_t"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"exception_behavior_array_t","preciseIdentifier":"c:@T@exception_behavior_array_t"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"exception_flavor_array_t","preciseIdentifier":"c:@T@exception_flavor_array_t"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"kern_return_t","preciseIdentifier":"c:@T@kern_return_t"}],"title":"task_get_exception_ports_info(_:_:_:_:_:_:_:)","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:@F@task_get_exception_ports_info","modules":[{"name":"NIO"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO"]]},"references":{"doc://org.swift.docc/documentation/NIO/exception_mask_array_t":{"role":"symbol","title":"exception_mask_array_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"exception_mask_array_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_mask_array_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"exception_mask_array_t"}],"url":"\/documentation\/nio\/exception_mask_array_t"},"doc://org.swift.docc/documentation/NIO/exception_handler_info_array_t":{"role":"symbol","title":"exception_handler_info_array_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"exception_handler_info_array_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_handler_info_array_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"exception_handler_info_array_t"}],"url":"\/documentation\/nio\/exception_handler_info_array_t"},"doc://org.swift.docc/documentation/NIO/kern_return_t":{"role":"symbol","title":"kern_return_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"kern_return_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/kern_return_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kern_return_t"}],"url":"\/documentation\/nio\/kern_return_t"},"doc://org.swift.docc/documentation/NIO/mach_msg_type_number_t":{"role":"symbol","title":"mach_msg_type_number_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mach_msg_type_number_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/mach_msg_type_number_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mach_msg_type_number_t"}],"url":"\/documentation\/nio\/mach_msg_type_number_t"},"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"},"doc://org.swift.docc/documentation/NIO/task_get_exception_ports_info(_:_:_:_:_:_:_:)":{"role":"symbol","title":"task_get_exception_ports_info(_:_:_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"task_get_exception_ports_info"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"mach_port_t","preciseIdentifier":"c:@T@mach_port_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"exception_mask_t","preciseIdentifier":"c:@T@exception_mask_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"exception_mask_array_t","preciseIdentifier":"c:@T@exception_mask_array_t"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"mach_msg_type_number_t","preciseIdentifier":"c:@T@mach_msg_type_number_t"},{"kind":"text","text":">!, "},{"kind":"typeIdentifier","text":"exception_handler_info_array_t","preciseIdentifier":"c:@T@exception_handler_info_array_t"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"exception_behavior_array_t","preciseIdentifier":"c:@T@exception_behavior_array_t"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"exception_flavor_array_t","preciseIdentifier":"c:@T@exception_flavor_array_t"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"kern_return_t","preciseIdentifier":"c:@T@kern_return_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/task_get_exception_ports_info(_:_:_:_:_:_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/nio\/task_get_exception_ports_info(_:_:_:_:_:_:_:)"},"doc://org.swift.docc/documentation/NIO/exception_flavor_array_t":{"role":"symbol","title":"exception_flavor_array_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"exception_flavor_array_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_flavor_array_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"exception_flavor_array_t"}],"url":"\/documentation\/nio\/exception_flavor_array_t"},"doc://org.swift.docc/documentation/NIO/exception_mask_t":{"role":"symbol","title":"exception_mask_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"exception_mask_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_mask_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"exception_mask_t"}],"url":"\/documentation\/nio\/exception_mask_t"},"doc://org.swift.docc/documentation/NIO/exception_behavior_array_t":{"role":"symbol","title":"exception_behavior_array_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"exception_behavior_array_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_behavior_array_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"exception_behavior_array_t"}],"url":"\/documentation\/nio\/exception_behavior_array_t"},"doc://org.swift.docc/documentation/NIO/mach_port_t":{"role":"symbol","title":"mach_port_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mach_port_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/mach_port_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mach_port_t"}],"url":"\/documentation\/nio\/mach_port_t"}}}