{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"task_set_exception_ports"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"task"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/task_t","preciseIdentifier":"c:@T@task_t","text":"task_t"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"exception_mask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_mask_t","preciseIdentifier":"c:@T@exception_mask_t","text":"exception_mask_t"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"new_port"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/mach_port_t","preciseIdentifier":"c:@T@mach_port_t","text":"mach_port_t"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"behavior"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_behavior_t","preciseIdentifier":"c:@T@exception_behavior_t","text":"exception_behavior_t"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"new_flavor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/thread_state_flavor_t","preciseIdentifier":"c:@T@thread_state_flavor_t","text":"thread_state_flavor_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/kern_return_t","preciseIdentifier":"c:@T@kern_return_t","text":"kern_return_t"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/task_set_exception_ports(_:_:_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/task_set_exception_ports(_:_:_:_:_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"task_set_exception_ports"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"task_t","preciseIdentifier":"c:@T@task_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"exception_mask_t","preciseIdentifier":"c:@T@exception_mask_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"mach_port_t","preciseIdentifier":"c:@T@mach_port_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"exception_behavior_t","preciseIdentifier":"c:@T@exception_behavior_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"thread_state_flavor_t","preciseIdentifier":"c:@T@thread_state_flavor_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"kern_return_t","preciseIdentifier":"c:@T@kern_return_t"}],"title":"task_set_exception_ports(_:_:_:_:_:)","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:@F@task_set_exception_ports","modules":[{"name":"NIO"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO"]]},"references":{"doc://org.swift.docc/documentation/NIO/kern_return_t":{"role":"symbol","title":"kern_return_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"kern_return_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/kern_return_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kern_return_t"}],"url":"\/documentation\/nio\/kern_return_t"},"doc://org.swift.docc/documentation/NIO/mach_port_t":{"role":"symbol","title":"mach_port_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"mach_port_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/mach_port_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mach_port_t"}],"url":"\/documentation\/nio\/mach_port_t"},"doc://org.swift.docc/documentation/NIO/exception_mask_t":{"role":"symbol","title":"exception_mask_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"exception_mask_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_mask_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"exception_mask_t"}],"url":"\/documentation\/nio\/exception_mask_t"},"doc://org.swift.docc/documentation/NIO/task_t":{"role":"symbol","title":"task_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"task_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/task_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"task_t"}],"url":"\/documentation\/nio\/task_t"},"doc://org.swift.docc/documentation/NIO/exception_behavior_t":{"role":"symbol","title":"exception_behavior_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"exception_behavior_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception_behavior_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"exception_behavior_t"}],"url":"\/documentation\/nio\/exception_behavior_t"},"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"},"doc://org.swift.docc/documentation/NIO/task_set_exception_ports(_:_:_:_:_:)":{"role":"symbol","title":"task_set_exception_ports(_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"task_set_exception_ports"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"task_t","preciseIdentifier":"c:@T@task_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"exception_mask_t","preciseIdentifier":"c:@T@exception_mask_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"mach_port_t","preciseIdentifier":"c:@T@mach_port_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"exception_behavior_t","preciseIdentifier":"c:@T@exception_behavior_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"thread_state_flavor_t","preciseIdentifier":"c:@T@thread_state_flavor_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"kern_return_t","preciseIdentifier":"c:@T@kern_return_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/task_set_exception_ports(_:_:_:_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/nio\/task_set_exception_ports(_:_:_:_:_:)"},"doc://org.swift.docc/documentation/NIO/thread_state_flavor_t":{"role":"symbol","title":"thread_state_flavor_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"thread_state_flavor_t"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/thread_state_flavor_t","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thread_state_flavor_t"}],"url":"\/documentation\/nio\/thread_state_flavor_t"}}}