{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error to use when exiting, if any."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the "},{"type":"codeVoice","code":"error"},{"type":"text","text":" parameter is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", this method prints nothing and exits"},{"type":"text","text":" "},{"type":"text","text":"with code "},{"type":"codeVoice","code":"EXIT_SUCCESS"},{"type":"text","text":". If "},{"type":"codeVoice","code":"error"},{"type":"text","text":" represents a help request or"},{"type":"text","text":" "},{"type":"text","text":"another "},{"type":"codeVoice","code":"CleanExit"},{"type":"text","text":" error, this method prints help information and"},{"type":"text","text":" "},{"type":"text","text":"exits with code "},{"type":"codeVoice","code":"EXIT_SUCCESS"},{"type":"text","text":". Otherwise, this method prints a relevant"},{"type":"text","text":" "},{"type":"text","text":"error message and exits with code "},{"type":"codeVoice","code":"EX_USAGE"},{"type":"text","text":" or "},{"type":"codeVoice","code":"EXIT_FAILURE"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/swiftdoccutilities\/doccarchiveoption\/exit(witherror:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/SwiftDocCUtilities\/DocCArchiveOption\/exit(withError:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Terminates execution with a message and exit code that is appropriate"},{"type":"text","text":" "},{"type":"text","text":"for the given error."}],"kind":"symbol","metadata":{"role":"symbol","title":"exit(withError:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"}],"symbolKind":"method","externalID":"s:14ArgumentParser17ParsableArgumentsPAAE4exit9withErrors5NeverOs0G0_pSg_tFZ::SYNTHESIZED::s:18SwiftDocCUtilities0B14CArchiveOptionV","extendedModule":"ArgumentParser","modules":[{"name":"SwiftDocCUtilities"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/SwiftDocCUtilities","doc:\/\/org.swift.docc\/documentation\/SwiftDocCUtilities\/DocCArchiveOption","doc:\/\/org.swift.docc\/documentation\/SwiftDocCUtilities\/DocCArchiveOption\/ParsableArguments-Implementations"]]},"references":{"doc://org.swift.docc/documentation/SwiftDocCUtilities/DocCArchiveOption":{"role":"symbol","title":"DocCArchiveOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocCArchiveOption"}],"abstract":[{"type":"text","text":"Resolves and validates a URL value that provides the path to a documentation archive."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/SwiftDocCUtilities\/DocCArchiveOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocCArchiveOption"}],"url":"\/documentation\/swiftdoccutilities\/doccarchiveoption"},"doc://org.swift.docc/documentation/SwiftDocCUtilities":{"role":"collection","title":"SwiftDocCUtilities","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/SwiftDocCUtilities","kind":"symbol","type":"topic","url":"\/documentation\/swiftdoccutilities"},"doc://org.swift.docc/documentation/SwiftDocCUtilities/DocCArchiveOption/exit(withError:)":{"role":"symbol","title":"exit(withError:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"}],"abstract":[{"type":"text","text":"Terminates execution with a message and exit code that is appropriate"},{"type":"text","text":" "},{"type":"text","text":"for the given error."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/SwiftDocCUtilities\/DocCArchiveOption\/exit(withError:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftdoccutilities\/doccarchiveoption\/exit(witherror:)"},"doc://org.swift.docc/documentation/SwiftDocCUtilities/DocCArchiveOption/ParsableArguments-Implementations":{"role":"collectionGroup","title":"ParsableArguments Implementations","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/SwiftDocCUtilities\/DocCArchiveOption\/ParsableArguments-Implementations","kind":"article","type":"topic","url":"\/documentation\/swiftdoccutilities\/doccarchiveoption\/parsablearguments-implementations"}}}