{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationError"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/argumentparser\/validationerror"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.swift.docc\/s23CustomStringConvertibleP","doc:\/\/org.swift.docc\/s5ErrorP","doc:\/\/org.swift.docc\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ValidationError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An error type that is presented to the user as an error with parsing their"},{"type":"text","text":" "},{"type":"text","text":"command-line input."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationError"}],"title":"ValidationError","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:14ArgumentParser15ValidationErrorV","modules":[{"name":"ArgumentParser"}],"navigatorTitle":[{"kind":"identifier","text":"ValidationError"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/ArgumentParser"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ValidationError\/init(_:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ValidationError\/description","doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ValidationError\/message"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ValidationError\/Error-Implementations"],"generated":true}],"references":{"doc://org.swift.docc/documentation/ArgumentParser":{"role":"collection","title":"ArgumentParser","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser"},"doc://org.swift.docc/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.swift.docc\/s8SendableP"},"doc://org.swift.docc/documentation/ArgumentParser/ValidationError/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The error message represented by this instance, this string is presented to"},{"type":"text","text":" "},{"type":"text","text":"the user when a "},{"type":"codeVoice","code":"ValidationError"},{"type":"text","text":" is thrown from either; "},{"type":"codeVoice","code":"run()"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"codeVoice","code":"validate()"},{"type":"text","text":" or a transform closure."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ValidationError\/message","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/validationerror\/message"},"doc://org.swift.docc/documentation/ArgumentParser/ValidationError":{"role":"symbol","title":"ValidationError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationError"}],"abstract":[{"type":"text","text":"An error type that is presented to the user as an error with parsing their"},{"type":"text","text":" "},{"type":"text","text":"command-line input."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ValidationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidationError"}],"url":"\/documentation\/argumentparser\/validationerror"},"doc://org.swift.docc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.swift.docc\/s23CustomStringConvertibleP"},"doc://org.swift.docc/documentation/ArgumentParser/ValidationError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ValidationError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/argumentparser\/validationerror\/error-implementations"},"doc://org.swift.docc/documentation/ArgumentParser/ValidationError/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ValidationError\/description","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/validationerror\/description"},"doc://org.swift.docc/documentation/ArgumentParser/ValidationError/init(_:)":{"role":"symbol","title":"init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a new validation error with the given message."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/ArgumentParser\/ValidationError\/init(_:)","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/validationerror\/init(_:)"},"doc://org.swift.docc/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/org.swift.docc\/s5ErrorP"}}}